# Use postgres/example user/password credentials
# https://hub.docker.com/_/postgres
# docker-compose -f stack.yml up
version: "3"
services:
    db:
        image: postgres:latest #postgres镜像
        privileged: true #解决权限
        volumes:
            - /opt/data:/opt/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: 123456
            PGDATA: /opt/data # 数据存储文件夹
        ports:
            - "5432:5432"
        restart: always
